[package]
name = "librespot-metadata"
version = "0.3.1"
authors = ["Paul Lietar <paul@lietar.net>"]
description = "The metadata logic for librespot"
license = "MIT"
repository = "https://github.com/librespot-org/librespot"
edition = "2018"

[dependencies]
async-trait = "0.1"
byteorder = "1.3"
bytes = "1.0"
chrono = "0.4"
log = "0.4"
protobuf = "2.14.0"
thiserror = "1"
uuid = { version = "0.8", default-features = false }

[dependencies.librespot-core]
path = "../core"
version = "0.3.1"

[dependencies.librespot-protocol]
path = "../protocol"
version = "0.3.1"
