[package]
name = "librespot-audio"
version = "0.3.1"
authors = ["Paul Lietar <paul@lietar.net>"]
description="The audio fetching and processing logic for librespot"
license = "MIT"
edition = "2018"

[dependencies.librespot-core]
path = "../core"
version = "0.3.1"

[dependencies]
aes = { version = "0.7", features = ["ctr"] }
byteorder = "1.4"
bytes = "1"
futures-core = "0.3"
futures-util = "0.3"
hyper = { version = "0.14", features = ["client"] }
log = "0.4"
parking_lot = { version = "0.11", features = ["deadlock_detection"] }
tempfile = "3.1"
thiserror = "1.0"
tokio = { version = "1", features = ["macros", "parking_lot", "sync"] }
