[package]
name = "librespot-discovery"
version = "0.3.1"
authors = ["Paul Lietar <paul@lietar.net>"]
description = "The discovery logic for librespot"
license = "MIT"
repository = "https://github.com/librespot-org/librespot"
edition = "2018"

[dependencies]
aes-ctr = "0.6"
base64 = "0.13"
cfg-if = "1.0"
dns-sd = { version = "0.1.3", optional = true }
form_urlencoded = "1.0"
futures-core = "0.3"
futures-util = "0.3"
hmac = "0.11"
hyper = { version = "0.14", features = ["http1", "server", "tcp"] }
libmdns = "0.6"
log = "0.4"
rand = "0.8"
serde_json = "1.0.25"
sha-1 = "0.9"
thiserror = "1.0"
tokio = { version = "1.0", features = ["parking_lot", "sync", "rt"] }

[dependencies.librespot-core]
path = "../core"
version = "0.3.1"

[dev-dependencies]
futures = "0.3"
hex = "0.4"
tokio = { version = "1.0", features = ["macros", "parking_lot", "rt"] }

[features]
with-dns-sd = ["dns-sd", "librespot-core/with-dns-sd"]
